### ISSUE TITLE
The fix doesn't work on Safari

### ISSUE THREAD

**Issue by Haroenv** [mathiasbynens/rel-noopener#1]
Both of the links make the page go to `#hax`.

Tested on Safari 9.0.3.

On Chrome it does "protect" the page

**Comment by LukyVj** [comment]
On my chrome ( 48.0.2564.116 (64-bit) ) it doesn't protect the page. 
No matter if I use the incognito-mode or regular chrome, if I arrive on the page, and click the `rel="noopener"` link, the page still got "hacked". 

[Gif demo with regular browsing](http://puu.sh/nHg5R/027f42e01b.gif)
[Incognito mode](http://puu.sh/nHg92/796a5d1d44.png)

**Comment by mathiasbynens** [comment]
@LukyVj As the page says, `rel=noopener` is supported in Chrome 49+.

@Haroenv [Safari hasn’t implemented `rel=noopener` yet.](https://bugs.webkit.org/show_bug.cgi?id=155166)
